In [4]:
import numpy as np
from hiernmf2.hier8_neat import hier8_neat

In [9]:
X= np.random.random([100,30])

In [10]:
X

array([[0.80359318, 0.89855977, 0.51847926, ..., 0.6392921 , 0.41856069,
        0.26938175],
       [0.30276571, 0.77600457, 0.09636822, ..., 0.22666858, 0.53688188,
        0.76220604],
       [0.47713264, 0.42612141, 0.4036018 , ..., 0.20176152, 0.86659862,
        0.20305628],
       ...,
       [0.26917567, 0.73184873, 0.3931291 , ..., 0.61203097, 0.75567279,
        0.01724857],
       [0.51258122, 0.69554258, 0.07172191, ..., 0.90998829, 0.48015951,
        0.05569071],
       [0.51704139, 0.22097239, 0.25764131, ..., 0.97625021, 0.57659607,
        0.34200189]])

In [12]:
tree, splits, is_leaf, clusters, timings, Ws, priorities \
=hier8_neat(X,9)

iterNumber 145
priorities [0. 0.]
splits [0]
tree [[0 0]
 [0 0]]
is_leaf [1 1]
iterNumber 194
iterNumber 110
[0.73616325 0.6755723  0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]
[0.73616325 0.6755723 ]
priorities [0.73616325 0.6755723  0.         0.        ]
splits [0 0]
tree [[2 0 0 0]
 [3 0 0 0]]
is_leaf [0 1 1 1]
iterNumber 185
iterNumber 129
[0.73616325 0.6755723  0.53050868 0.64697347 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]
[0.6755723  0.53050868 0.64697347]
priorities [0.73616325 0.6755723  0.53050868 0.64697347 0.         0.        ]
splits [0 0 1]
tree [[2 4 0 0 0 0]
 [3 5 0 0 0 0]]
is_leaf [0 0 1 1 1 1]
iterNumber 79
iterNumber 159
[0.73616325 0.6755723  0.53050868 0.64697347 0.62669431 0.57399292
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]
[0.53